### ISSUE TITLE
Some improvements suggestion

### ISSUE THREAD

**Issue by epfly6** [Kevadroz/tboiAchievementUnlocker#2]
1. You can use ItemConfigItem method IsAvailable() to check if achievement locked items is unlocked or not
https://wofsauge.github.io/IsaacDocs/rep/ItemConfig_Item.html#isavailable

2. And so for that reason, you can delete the itempools xml, since it's going to be unnecessary

**Comment by Kevadroz** [comment]
Suggestions taken and implemented in commit 1dddc21ccb74cc1590bff5d94e1fe2a190136944
